name: RAScript Audit
description: Compiles RAScript for RetroAchievements development and performs an audit on the code.
author: joshraphael

inputs:
  game-id:
    description: "RetroAchievements game id"
    type: number
    required: true
  rascript:
    description: "The RAScript to compile"
    type: string
    required: true
  report:
    description: "Create a report of the audit"
    type: boolean
    required: false
  severity:
    description: "Level of severity to fail on"
    type: choice
    required: false

branding:
  color: blue
  icon: award

runs:
  using: "composite"
  steps:
    - name: Set Environment
      env:
        RATOOLS: v1.15.0
      id: env
      shell: bash
      run: |
        echo "RATOOLS_VERSION=${{env.RATOOLS}}" >> "${GITHUB_OUTPUT}"
        echo "RATOOLS_DIR=~/Installs/RATools-${{env.RATOOLS}}" >> "${GITHUB_OUTPUT}"
        echo "RALIBRETRO_DIR=~/Installs/RALibretro-x64" >> "${GITHUB_OUTPUT}"
        echo "DOTNET_ROOT_X64=C:\\Programs\\dotnet" >> "${GITHUB_OUTPUT}"
        echo "DOTNET_ROOT=C:\\Programs\\dotnet" >> "${GITHUB_OUTPUT}"
        echo "WINEPATH=C:\\Programs\\dotnet" >> "${GITHUB_OUTPUT}"

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23.0'

    - name: Create folders
      shell: bash
      run: mkdir -p ${{ steps.env.outputs.RATOOLS_DIR }} && mkdir -p ${{ steps.env.outputs.RALIBRETRO_DIR }}/RACache/Data

    - name: Install wine
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y wine

    - name: Set Winecfg
      shell: bash
      run: winecfg /v win10

    - name: Get RATools CLI
      shell: bash
      run: wget -O ${{ steps.env.outputs.RATOOLS_DIR }}/RATools-${{ steps.env.outputs.RATOOLS_VERSION }}.zip "https://github.com/Jamiras/RATools/releases/download/${{ steps.env.outputs.RATOOLS_VERSION }}/RATools-${{ steps.env.outputs.RATOOLS_VERSION }}.zip"

    - name: Unpack RATools
      shell: bash
      run: unzip ${{ steps.env.outputs.RATOOLS_DIR }}/RATools-${{ steps.env.outputs.RATOOLS_VERSION }}.zip -d ${{ steps.env.outputs.RATOOLS_DIR }}

    - name: Get .NET SDK 6.0.428
      id: dotnet-sdk
      shell: bash
      run: ./dotnet-sdk.sh